using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ModCodeItem : CodeItemBase {
    //模块（if、while）
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    public override string Parse()
    {
        return base.Parse();
    }

}
